Prepare for 3.2.0.Final keycloak deployment
fabric8-services/keycloak-deployment pull request #34
Opened 2017-07-12 10:05 UTC by sbose78

- Modified `git clone` steps to use the tag 
- Modified the dist name referred to, in Dockerfile
- Modified the `standalon-*.xml` files to keep the changes made by OpenShift.io team, but discard the changes specific to wildfly versions.

2017-07-12 12:13 UTC, sbose78 commented
- compiled and created https://hub.docker.com/r/sbose78/keycloak-3.2.0
- deployed on http://keycloak-test-kc.dev.rdu2c.fabric8.io

Tested out the following 

- token generation using `grant_type=password`
- Space creation  :  `./bin/wit-cli create space --key $ALM_TOKEN  --payload '{ "data":{ "type":"spaces" ,  "attributes":{"name":"testuser-space-1"}}}' -H localhost:8080 --pp` This covers a lot of endpoints.
- Collaborators : `./bin/wit-cli add collaborators --key $ALM_TOKEN  --spaceID "5d8165b7-e07d-463d-b940-111fb2aae3dd"  --identityID "ac5a1aee-1aae-4bbb-a21a-0f1e4d081a46"  -H localhost:8080 --pp`
- Login : Tested out login using Facebook.
- Linking : Tested out linking github.

2017-07-12 12:15 UTC, sbose78 commented
[test]

2017-07-12 15:26 UTC, sbose78 commented
A couple of kerberos related tests are failing .

2017-07-12 23:07 UTC, alexeykazakov commented
@sbose78 I don't know why but these tests always fail here. It's not critical bc the same tests pass in fabric8-services/keycloak in Travis. Don't know why the same tests fail in centos-ci.
So, it's not a blocker for this PR but we need to investigate and fix it (separately).

2017-07-14 08:43 UTC, magick93 commented
@sbose78 - Firstly, apologies for writing here as my question is not directly related to this PR.

Im interested in using sbose78/keycloak-3.2.0. However, I couldnt find the source for this. I am trying to understand what env vars are needed to run this in Openshift. Can you help?

2017-07-14 08:50 UTC, sbose78 commented
Hi @magick93 , Do you mind heading over to the #keycloak  irc channel on freenode ? I could assist you there :)

2017-07-17 08:18 UTC, hectorj2f commented on docker/standalone.xml
> +        <subsystem xmlns="urn:jboss:domain:ejb3:4.0">
wow, the downgrade the version... that is weird

2017-07-17 08:19 UTC, hectorj2f commented on docker/standalone.xml
> +        <subsystem xmlns="urn:jboss:domain:datasources:4.0">
also here ?

2017-07-17 08:19 UTC, hectorj2f commented on docker/standalone.xml
> +<?xml version='1.0' encoding='UTF-8'?>
Did they add this encoding ?

2017-07-17 08:20 UTC, hectorj2f commented on docker/standalone-ha.xml
> +                <datasource jndi-name="java:jboss/datasources/ExampleDS" pool-name="ExampleDS" enabled="true" use-java-context="true">
We don need this

2017-07-17 08:21 UTC, hectorj2f commented on docker/standalone-ha.xml
> +            <periodic-rotating-file-handler name="FILE" autoflush="true">
We don't need to configure any file handler

2017-07-17 08:23 UTC, hectorj2f requested changes
I made some questions and asked for some changes

2017-07-17 08:23 UTC, hectorj2f commented on cico_setup.sh
> +  git clone -b 3.2.0.Final  --depth 1 https://github.com/fabric8-services/keycloak.git
Just a question, I might miss something but we're not using on purpose `master`. Why do we want to start using again different branches ? @alexeykazakov

2017-07-17 08:36 UTC, sbose78 commented
Hi @hectorj2f , I took in the changes from the `standalone-*.xml` created in the distribution/server-`dist/target/keycloak-3.2.0.Final/standalone/configuration/standalone.xml` . That's where the changes in version ( downgrading ) was present. I'm guessing the downgrading is because they moved to wildfly 10 instead of 11 ?

2017-07-17 08:37 UTC, sbose78 commented on docker/standalone.xml
> +<?xml version='1.0' encoding='UTF-8'?>
I found this change in the generated `distribution/server-dist/target/keycloak-3.2.0.Final/standalone/configuration/standalone.xml`

2017-07-17 08:37 UTC, sbose78 commented on docker/standalone.xml
> +        <subsystem xmlns="urn:jboss:domain:datasources:4.0">
I found this change in the generated `distribution/server-dist/target/keycloak-3.2.0.Final/standalone/configuration/standalone.xml`

2017-07-17 08:37 UTC, sbose78 commented on docker/standalone.xml
> +        <subsystem xmlns="urn:jboss:domain:ejb3:4.0">
I found this change in the generated `distribution/server-dist/target/keycloak-3.2.0.Final/standalone/configuration/standalone.xml`

2017-07-17 08:46 UTC, sbose78 commented on cico_setup.sh
> +  git clone -b 3.2.0.Final  --depth 1 https://github.com/fabric8-services/keycloak.git
Here's some context about how we arrived at this : https://github.com/fabric8-services/keycloak/pull/93#issuecomment-314536967

But I feel slightly stronger about having the branch deployed into production, that way.. if we push to https://github.com/fabric8-services/keycloak-deployment 's master, we needn't end up deploying changes in https://github.com/fabric8-services/keycloak 's master.

2017-07-17 08:57 UTC, sbose78 commented on docker/standalone-ha.xml
> +                <datasource jndi-name="java:jboss/datasources/ExampleDS" pool-name="ExampleDS" enabled="true" use-java-context="true">
Thanks for the review, will remove. This came in as part of `distribution/server-dist/target/keycloak-3.2.0.Final/standalone/configuration/standalone-ha.xml`

2017-07-17 08:57 UTC, sbose78 commented on docker/standalone-ha.xml
> +            <periodic-rotating-file-handler name="FILE" autoflush="true">
Thanks for the review, will remove. This came in as part of `distribution/server-dist/target/keycloak-3.2.0.Final/standalone/configuration/standalone-ha.xml`

2017-07-17 09:01 UTC, hectorj2f commented on docker/standalone.xml
> +<?xml version='1.0' encoding='UTF-8'?>
Alright! I just wanted to be sure ;)

2017-07-17 09:04 UTC, hectorj2f commented on cico_setup.sh
> +  git clone -b 3.2.0.Final  --depth 1 https://github.com/fabric8-services/keycloak.git
Okay, it is clear now, :+1:

2017-07-17 10:15 UTC, sbose78 commented on docker/standalone-ha.xml
> +                <datasource jndi-name="java:jboss/datasources/ExampleDS" pool-name="ExampleDS" enabled="true" use-java-context="true">
removed here : https://github.com/fabric8io/keycloak-deployment/pull/34/commits/ae0e9ff575e1a835afc2c525826f62ffd6e92ec7

2017-07-17 10:17 UTC, sbose78 commented on docker/standalone-ha.xml
> +            <periodic-rotating-file-handler name="FILE" autoflush="true">
removed https://github.com/fabric8io/keycloak-deployment/pull/34/commits/fb8b1a64d7438f3fab5457daf472e7dab0ad8fb7

2017-07-17 10:35 UTC, hectorj2f commented on docker/standalone-ha.xml
> +                    <handler name="FILE"/>
Let's remove the creation of a file handler for the logging. It takes a lot of resources from KC which already uses a lot. We don't make use of the FILE handler but let's avoid its creation.

2017-07-17 10:36 UTC, hectorj2f commented on docker/standalone-ha.xml
> +            <default-bindings context-service="java:jboss/ee/concurrency/context/default" datasource="java:jboss/datasources/ExampleDS" managed-executor-service="java:jboss/ee/concurrency/executor/de
This will fail because the datasource exampleDS doesn't exist anymore

2017-07-17 10:37 UTC, hectorj2f approved these changes
I added two minor comments. We should test that this image works. Did you try it @sbose78  ?

2017-07-17 10:40 UTC, sbose78 commented
I am testing it end-to-end @hectorj2f after the new changes , will update here when done.

2017-07-17 10:41 UTC, sbose78 commented on docker/standalone-ha.xml
> +            <default-bindings context-service="java:jboss/ee/concurrency/context/default" datasource="java:jboss/datasources/ExampleDS" managed-executor-service="java:jboss/ee/concurrency/executor/de
Thanks, removing it, and testing it out.

2017-07-17 11:20 UTC, sbose78 commented on docker/standalone-ha.xml
> +            <default-bindings context-service="java:jboss/ee/concurrency/context/default" datasource="java:jboss/datasources/ExampleDS" managed-executor-service="java:jboss/ee/concurrency/executor/de
removed : https://github.com/fabric8io/keycloak-deployment/pull/34/commits/3f8153d88b0cbdd15a0aac5919b3b567458b8593

2017-07-17 11:52 UTC, sbose78 commented
Did the following after making the recent changes : 

- created an image by doing a `$ docker build --tag sbose78/keycloak-3.2.0 . ` 
- deployed it on the dev cluster
- check the server version deployed from the keycloak UI ( to ensure its really 3.2 ;) )
- ran tests against `fabric8-wit` & tried out space creation.

All looks GREEN to me.

Is this the right way to test , @hectorj2f  ?

I was wondering if I should deploy the image which was generated as part of this PR's CI kick-off ?

2017-07-18 19:17 UTC, hectorj2f commented
@sbose78 if you play with fabric8-platform and it worked it is good. But, perhaps, we could also try in clustered mode.

2017-07-18 20:14 UTC, alexeykazakov approved these changes

2017-07-19 10:26 UTC, sbose78 commented on docker/standalone-ha.xml
> +                    <handler name="FILE"/>
https://github.com/fabric8-services/keycloak-deployment/pull/34/commits/308efcfdc487c07ae6f1d5d508a117c1aafb67c9

2017-07-19 11:44 UTC, hectorj2f commented on docker/standalone-ha.xml
> -            <logger category="org.jgroups">
you removed this ... that we added before

2017-07-19 11:46 UTC, sbose78 commented on docker/standalone-ha.xml
> -            <logger category="org.jgroups">
This wasn't found in the 'new' `docker/standalone-ha.xml` when i did the build. Should I put it back?

2017-07-19 11:51 UTC, hectorj2f commented on docker/standalone-ha.xml
> -            <logger category="org.jgroups">
yes, we added to check things at infisnispan level. This is a temporal change that we need to evaluate the errors in the clustered mode.

2017-07-19 12:17 UTC, hectorj2f commented
lgtm

2017-07-19 12:27 UTC, hectorj2f commented on docker/standalone-ha.xml
> -            <logger category="org.jgroups">
@sbose78 why don't you add it ?

2017-07-19 12:49 UTC, sbose78 commented on docker/standalone-ha.xml
> -            <logger category="org.jgroups">
https://github.com/fabric8-services/keycloak-deployment/pull/34/commits/ac52da3b284b7f533c03e25823be9a8ff81f5146

2017-07-19 13:00 UTC, merged